contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #varanibu channel"
    url: https://nfcore.slack.com/channels/varanibu
    about: Discussion about the nf-core/varanibu pipeline
